# Generated by Django 3.2.23 on 2023-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ccode', models.CharField(max_length=100)),
            ],
        ),
    ]
